### ISSUE TITLE
Remove omit-deep dep?

### ISSUE THREAD

**Issue by emn-dev** [elrumordelaluz/svgson#53]
Use our own function to remove the parent prop, e.g.
```
export const removeAttrs = (obj) => {
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i++) {
      obj[i] = removeAttrs(obj[i])
    }
    return obj
  }

  Object.getOwnPropertyNames(obj).forEach((key) => {
    if (key === 'parent') delete obj.parent
    if (obj[key] && typeof obj[key] === 'object') removeAttrs(obj[key])
  })

  return obj
}
```

The omit-deep package has dependencies itself, namely https://www.npmjs.com/package/unset-value , and that package had some security audit/warnings recently. It has been updated but do we need all the other packages to remove the parent property?

I'm not exactly sure why we need to remove it in first place?

**Comment by elrumordelaluz** [comment]
This sounds absolutely valid as an alternative of `omit-deep` for this case! 
In fact, you found another important point: since is set to `parentNodes: false` when parsing the input, we are removing the `parent: null` (will be always `null` due to the options passed) as an stylistic choice. We can leave it as it is (with `paren: null`) without problem, avoiding an extra step, eliminating external libs and reducing lines of code. Great!
